# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:BSu/DKM7pvrUl4Be3HHY433oOsoH9mC8jBhSCiEqqRH6vz00Io15E4s+mD1fark9H8fetYnBf3143iwDScLLO6M4YQpERTt09nPqGp4xzlsegK4yKzP7EwUjGWHBMvv2G15XZvmi67/8vzEnapYV2C+f9b+hO7Bly0+m8xabVqxQ+NOX4BL1Dd91roruIa1KNfdM8MUyGTf+GJ7o0miVULvs1MmN/A7OobHWhc+q4pf+szhACg==,iv:UV/PF4UGLZj6OjXIbhJmo2V4hb3hPFfSMZB5pfBBp38=,tag:PjJTwG3dymYcKCgrB1mt/A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1r9x82vylxeu648374ysaydeawu0a2xankc3fclw060ps2cqrsucq4zwtd5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbnJTdTlrSk5KMTc0eXNs
        QjFVTXdQNTRTQllyNnNSbSt3TUJsV0ZvY0ZFCjJFODJvbVNuendNMGdwN2lvbkZv
        cUNTL3NVNWwxT1dPZ2tqYXlGNysxY1EKLS0tIHRTSVFpdmVIUGMxbWlvRk1kTUs1
        UEplMlZROFROZE9HVWdqMlZTb1FoWVEK760QGDnvu6CAyvKaiL7bvm24pTQsW4lH
        Mpk1y2u60v/Tg/+cv69YnqOGEdIqJjwd73yZb2WTCDdK7XtOn+rBYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-06T20:11:43Z"
  mac: ENC[AES256_GCM,data:bXcwXEEjje9T1YLvWFUPTWZ9m0CDk00aIn+GwzU19tKMrMQFaorNep/nObyIgb974ximE8eWEBxSwQu3bMjuTIVSs3yiDxT6wOx4aEKNIHmThTatxnE9Ikbe09r/A4i8wT/sLGjeSqh5a7R17Ww7baw3ATuWhPMkxdt5yw5pwX8=,iv:XVsFZbn8D7bolZZI7gqGYJblISAVR6QtN4z37kuAOL4=,tag:q3matcGgyYaGwq9HRch2ZQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
