# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:rhLw4opKBWpQUEltZCoHDkzv2lN+3uslMDCfAi10cZtNNBHm4iJ8sA==,iv:/Et5IYarckSK9c/FNyH/Xq1Q+SrpMtWg4A0S88UnIpw=,tag:FWGbz7mErqFVfbtiHT/IPw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1r9x82vylxeu648374ysaydeawu0a2xankc3fclw060ps2cqrsucq4zwtd5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQLzJDeEFJR0t0MXJWOGV0
        QzRuNHJNRFNOTnhEZWdrSVdMdXNPRTZUSkhJCmNOclZUb0dCdFozc0R5RnNJTlRk
        c0crYkh0N2oxWGJuajI1VFdhT05TbEUKLS0tIER0ZGNmNTNzY1RhZ1VEejFJK3lI
        dG14eVVGeW1BU1Y0dFRBWEZjWnZWMFkKqsmPxt5BEUhy9bdlHXWBsFl+f6c8xKnC
        bLE9NRQZoAjYpDO4UlUoALsPK28XGpTwABlOVavPNdZMWVf7YaSJZw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-06T20:11:43Z"
  mac: ENC[AES256_GCM,data:eQqPV1Q4PerAVyp8pNn5bmvjP8Ho33/l+Um0gERK/JmidYQ3IeZvbG2F4LE6AtTAn1MUgAZpPiroLBLYNRvksIgRBVLr/9XNKT7o+ODrW52/JLJVcFgyFtHrUjhV9SZ1ZCY6xzmXVC0CxfwS2OVCcKj8cyDLt9w7jACG3u00Y0o=,iv:utsjplr4pkdq4nkoh6XlNVqci0l3BJhY6dPe1BiwyXE=,tag:qEDPBO3U3we66c0e6BFrvQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
