---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich
spec:
  secretName: immich-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "photos.${SECRET_DOMAIN}"
  dnsNames:
    - "photos.${SECRET_DOMAIN}"
