apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:kxrD8UnphfYv3gTXkb6Ymf2r3HPPryvcbKRxUOQg+JHtgsOi,iv:pxe0+BiVkZ0Ck0oLzgFHL2Ovb3WRHnxVL6NAHrVnBOM=,tag:+VBxTLPbm/6B5n4HM0LwKA==,type:str]
  credentials.json: ENC[AES256_GCM,data:HRRBbKVPMWH0r67JkDnOZrzyNLNnR16UmbUjCW9hw0xilA69Uz6evcBV8p3CPWPqUjZ+WWa0rd1b+xJYFfkpymun2SkL9VvHKYdqPn74DUhAEKhY+RquzYplbsv1dcD/jhezV33BQsh7LY+Z9nkKYXJ/qwPquj//MTPP0XMBanQbvhqBpYQxQ+oA/vRsUOLvT9h1Jo27ky4PwGNnv8IciOzh1rKK9UtKF0GS5PDlXQ==,iv:z2YOP7IXXjyYwr+Wsjno1ExO3djdnGIt7wcd1QMZBTs=,tag:wmr2lgKG4shXz6j1ZOrUgA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18rs8lggg0adpzfkgpz5zgja9ayu5d9m3hzedwr6vyjrzj4h3afss5jxglt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRklNODdaZ0UrejRVbTFQ
        TmtjbVN2RkxZZWEwWmF3MjJOWmFsYm93K0U0ClRYcTlVTVNUUkI5aURLd2tYM1F6
        MkNScEp4bS9zRE1hMHVrZHhzN3lTekUKLS0tIHh5ZDFnYkg4V243TzRnQjhXZEpH
        ZVpFTFQ2cG85MlRHTGVLRE9xUnhPRWMKnnPFrL3SL2u2xi2wlpIxZ7uZ2EOmuqkp
        m2uzGZoFdUO/QRYZO8UNaKM1oZQ90UGOlMxxAAecIgscGThuUHWk5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-09T06:38:28Z"
  mac: ENC[AES256_GCM,data:thy8knb0XSBoURsDZecw7Gu1KbcBRrHv6fZ3+24vtXu985KbuD+I00vtnnNnLSCIK09fMAgvPQ2rLhW7RAWIlrKcHFQ8Su+ZpRa57wihjgDD9gNZaM9YMEG9oj9nFe6dmFcZ3oF0uesaB9lZS98jHKrb9PEgpTxTb1gqS5Bmf58=,iv:sWHbM7d9Hp3W525JhjgaHCVo4x/pH6lyzDT7LV4AFRI=,tag:wtXh61J5EVJgfy3MFMyuuA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
