apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:l2cVVGz9hI7MyJHYZ9HJ8zhd4eKiG/PiSjuzb9fAgfzSC2ds,iv:Qe4xFKZOUJPLNMVmDj1JHKvbngQKfg1SDP8q76nSJ3o=,tag:iHgFVkDdVrfukqnMPgzMnQ==,type:str]
  credentials.json: ENC[AES256_GCM,data:4fodGg9lU9FQh5j4WOSGFY3W7NCnhdPuqYn9Kq0oEPVlanPafl0/+DVfuU7rM0x+7jvei0PUL0nI+eWnqSBj5FRXHj0gSe0mBTPnnGd99V7tPcPpMMPoBRpqRHuLFFkBldd4qgoFHWfJ6H5jZwQdurDDoslSGyNN4QO1bBi9PW57RLTEFbDSlpXFJ0Hz7wngyWmmWeF+yP9Jt+rwpWQSyCTXSKWCwPMT8BQHtkrd0A==,iv:C2VLAqnR3Tn4jkDmZpN+BC7W38+2bdgEVQTt4NjCgQs=,tag:tTsVX7iWEhFpTjFNujlvEg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18rs8lggg0adpzfkgpz5zgja9ayu5d9m3hzedwr6vyjrzj4h3afss5jxglt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArc2h0bDZia3JyTzdmT1FW
        a3VLdVdUblU4N1creFlOMmw3STV3TzdpMTJjClc4MGFLd3NQZkl5SW1wQ1FSK3Zk
        YnNTakQrV0Q0K3Z6L3hLSXBSWHhtckEKLS0tIHNQOWlhMSthaVpFNS9XRm4wcCtT
        S05JWi9aanJiTHJDY1A2L0JQTEFGMzgK0EItT0ZdJWoz4r9aCXZ/AiS7cGjpTHeB
        0ZI+qigQAu9sWjTLXGzzLNnc0jD3c6/W4tWvydHVewiWi9GGfswkAA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-09T08:44:49Z"
  mac: ENC[AES256_GCM,data:fWacaHmIvbe2AkAN59Qt22wxm4/7S4w1PbP5wZsB9VlwO3QlvRYVTUqtcSKfXe++mWTxwx2NWc9ABxlOFXgQKu64l7GT61DlNngwBNyATQIBzeF/iYF3YLF8sbx3R+jjKCjomk3CIvQsEAC5mnY1a5cysH9Pbkb90SAOHSu6tJY=,iv:IogMCZGDF7v+PRnID5ls0sLRK1cUBr2gV8c4HPzrbig=,tag:iWcBySNMZT4PZWCzjThxKw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
