apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:1/6+MT6OnPhXwJ8c/+bzObY0+iu2epKTS8ry4STzXsI=,iv:vEIQAG3p/jR0d5wCc0oSRrnZwIU+pkacgBmogw+fsrE=,tag:HFpsEJJPYbbCb0R/zbnbnw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18rs8lggg0adpzfkgpz5zgja9ayu5d9m3hzedwr6vyjrzj4h3afss5jxglt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTmdZSnVsMTR3L09ISWEz
        WXpwNmFaNUdERzE3Z3ZFYkZ6NkVTem1ybkJVCkdHV3dVWGJoSEo4U1BJTlNzNGxJ
        Rkl0ZjNvV01DTHRHZ2d3cVRxWVB6dTAKLS0tIFNHak54NTVzU1NpWW5QZDVDVnN3
        YUg3eTkzKy9ZWG1SUUpNV1ZhVXJJdXMKZZoaoSbQURLvVxHSgkIdT7KIiFrOAG1R
        ufLqdw6bJwex2zlMzZeYAtBk8OS9v83Jsy6j7mtWaLD+2YKbeNetKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-09T06:38:28Z"
  mac: ENC[AES256_GCM,data:9U3CEGbmfefxvtRUVfftYJJC0hn4raHIPJQfmEkBfn4LQr65rqEeQpCi3LrbaYMaeIYouZRKdxbt/Cg2aKNW+4tFmxmlrm/bLFbIXaa04EvQv/dNvHIDqTC1HMiSI60eYSHB6QV6rIsIIV6H+OAv770A8LDQLcRuGNZqjryv5oc=,iv:BKFgpfY/Y/BTZ+aLNkeI0hvus/oeoY/r2ead0Hys6Ug=,tag:lB2N4/63pNSp8+NbqKXSsA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
