apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:WfE+NIKsRgzfVQIKwCV20FN0FS1SA2/COMrl8ky+QCo=,iv:zP3Kw8ZK8+g9uS6s0SSKVmZH1OGAQNrU+Rd9q5/ShyM=,tag:5m4nDmPvypOkIIdiCaaJyQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18rs8lggg0adpzfkgpz5zgja9ayu5d9m3hzedwr6vyjrzj4h3afss5jxglt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNzZCKzg2dG1BWHFITGZX
        WWVZdmNtS2hKczBYelVEOG9xb0tXcDNFZ2hrCk9sV21UTC84S2t6RzVyOWJWZXBq
        TGNNWTk0TGs0RVFxVnlUVUJDcnBMRHMKLS0tIHBkWUJraWhVY293bU5EMTJLaEdw
        dlFlSlBoTVRrVnYrc29FZUU2V2d0NTgKnkXkihRD6GJvoQBPbg8uOZi+fvc6vRmd
        nvLF/udivoIK1hQPBOrql0eDpg84k3XgnqavRgp9xbg0br0rhJHaIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-09T08:44:49Z"
  mac: ENC[AES256_GCM,data:qKnCCpluhdwLfOSG+8Qxf1FDqAHB7NpNIVZhHj+m7Eq0nkKmCota2cIC3BeZkmOSBsXn5efVueC+iC+RCKwBbrVoDzR/iEo3l51mg3ZXBDLFtcNEuXXv4bWbsft/69KROfPAJx2kuKp86hPgbJTaX/BSmjygo8WywNBg59cCj3U=,iv:6wQy4TAITq3pF70waBTk/W6bUDr7KOd/DWx29TCHhsY=,tag:i8b5KvJuVMW1JiZ7J471/w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
