# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:K81VFd2bRVuwXUkUMWAQVqP9aTiOW58A4+mOZhYJgpI=,iv:w0auxHHl4jf2TYRNB0FCFvusXhxpaMiLOSXPH3/5wbI=,tag:JGsj8KBwp+DucL4RJKn84g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1r9x82vylxeu648374ysaydeawu0a2xankc3fclw060ps2cqrsucq4zwtd5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdTZqZncvMllaOUNMRnBh
        WCtYdVFHNmtNbnJTZkJxMk94MEpSa21lM25BCjdoWUs3cVR6dzA2NlVmb29XdkR2
        Q1Naa0lmTW5wQ3RlZjlvbEg0aWlja28KLS0tIEhVcW4wdW8yY0xUU001dCtJWlFQ
        YWlKY0pXUklNMUNJOE0vb0wwU0NGT1kK9CD0kPOTaHIHomTKmiaVo0nwnOYlxEq3
        aj2yUEXDnCFdQph/wzElkOHtXmAgonxfq85LhGQpp/uUkYszH1/dXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-06T20:11:43Z"
  mac: ENC[AES256_GCM,data:meC5bzsu1Ms/0Ofnud7WupHq7Ot1mkZI1Y79Wi/l8urOd9uEy7zf0/DDEKwzaVho2f1QaNy4FDiR5wHI+ln9eCyPPmauCkXzST4+Ec5RUPCNwS/RRxcVKILnwghfrSgnfbeC1aH0FPDDyJx6CC9DVvReEM2fiBj7ZDiPzhwNwGg=,iv:hXlyyq8xyGFRDHq0V0rhxlWaVZZlowOSjgj6hVtH9Qo=,tag:VNxhYkFjORNteUSBLbLEQg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
