apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:TznPafAlIbYG9XMVfCN3ASAr1J1Ry4fZA4B+toND+vEN6KQ7vOAUPg==,iv:CGyY8PDuCPwD/s3nfL+wYtFCSZm/UbMRNjkN4cdAn9E=,tag:G0mPPV30PhPlrC6TgYUPNg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18rs8lggg0adpzfkgpz5zgja9ayu5d9m3hzedwr6vyjrzj4h3afss5jxglt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WjByUVZUS3Y1Mi9EWElR
        QW1KUHd2bHpCTG13dTZ3V0xkYnF0d05sMUJVCjZodjdleEhxbk9zOTBDV3dubHoy
        WWxaZ2ZoSEtTbG5kTHJjbUVJcGlDL00KLS0tIHQwR25tbXh6bkJSZkxZQTZQMXBV
        UWpMU0Y3QlBDRUdNdTZvNVdDQjFwTGMKtXPnlkdHTYTtANbmxDcZdSbjiSna62HK
        /iLZgV64LoV0mp0MZWEmGJL9o0W6a4atvB4U/OhNPhmdB0LfJEvr5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-09T06:38:28Z"
  mac: ENC[AES256_GCM,data:+/VDKOtLjjBnnFidNRGCE/JK0EQe3GuaHrzo04FJEa9z1iX2a3VBf8P5UGaUfYAx8c4exioBxxGI2QM3jsk1j4OIItdYB4/zrbOcfnystCPJq8PTT9MRy2OhHfNus9iHqkUXqUA1I2XdkllFVz4LvhZLsqcrzm6Z0FWTWE8O+ZU=,iv:EXJHfAv1MqKhdoReLaT9FpUPuC0jvY5aJOJon9KE2Qk=,tag:bPJgDZvrRhMUh+uX8tEtgw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
