apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:D+5/Q9SeaG+FFUHHtW/3V0+/QoM3qmYX2UUnM7pAZ/ewA6gtE+HbKw==,iv:Stted3mh7G1gdn1dU9I4klXQ2yqFK1QmxEHovVmAL9Y=,tag:thfpamwenuwF0RonTkGDfg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18rs8lggg0adpzfkgpz5zgja9ayu5d9m3hzedwr6vyjrzj4h3afss5jxglt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjclRxcEkxNG0rTWdGR3ZM
        eVE4NVBlM1JxSC9jb25xYTJ0aytqSW1KWm1ZClE2bzRkYVVTb3ovc2puc21UQTVD
        VTlnVm9SZ05EQlNVZHltakdKQ1N2YzQKLS0tIEFDaHBNWDhycWdPR3JwR1pMMGkv
        MTNmVWRGbzZ5c3RnNU1VYjIwV3JKLzQKCCxLVWwV+zOG568ktzlYkOC99/APV31y
        wCWDKKCQbm1z+JR6i15MlhDFMxdzdUlnhVDrTx+G39wCKS5eCmQmaw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-09T08:44:49Z"
  mac: ENC[AES256_GCM,data:rxM/EAbq6hSkoTDD2f771NcFwzXy+xS8UOFLHxhTTZzEmet1InyzWVYlIEJqJXr6bANgsjQ6DSiF7f38NeLzT9N6BETCNB4nSvgn8f3DQrEtsB7cWv+hF5+rDjUbDWO1+HLcspHEjwC1wQlCRZB4cnFbp61i/9cChwAhNV+20a4=,iv:zD2Qs3AX1C0pWn8rqSurtHSt6iePOYT9jAd4QT65AgI=,tag:0G8xFDesSlJwl/clZj8LLQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
