---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 1h
  chart:
    spec:
      chart: openebs
      version: 4.3.3
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  maxHistory: 4
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
          keep: false

    engines:
      local:
        hostpath:
          enabled: true
        lvm:
          enabled: false
        zfs:
          enabled: false
        rawfile:
          enabled: false
      replicated:
        mayastor:
          enabled: false

    localpv-provisioner:
      enabled: true
      hostpathClass:
        enabled: true
        isDefaultClass: true
        name: openebs-hostpath
        basePath: /var/mnt/openebs-localhost
        nodeSelector:
          openebs.io/local-hostpath: "true"
      analytics:
        enabled: false

    loki:
      enabled: false
    minio:
      enabled: false
    alloy:
      enabled: false