# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:QkXmPHbz7YEfFFlFu13tJPis2iknpISuMlwzNoZTDp+goHVQF5l11A==,iv:HjUYbj2tBhxN/+UgxLAhvncrE76NhulDNJFarRjZmqI=,tag:MYrIhRtthYgbbm58mLwhWQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1r9x82vylxeu648374ysaydeawu0a2xankc3fclw060ps2cqrsucq4zwtd5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRVN1RDI1Wmwxam40cHpS
        WHcwRFFwZmc3SkdWTURsWXlGdTNKTElvWW1RClJaWVczYzduZDhrMEU2TFp1ZTBK
        U01IK2lvYlhJK1dsVURwV0x6R3NBTlkKLS0tIGYraWNiSDZJdGlXUk03M2NWbUMz
        WU50MzRiUysvaUtzamJvL2N2Q1laQ1kK0AaKU/Kto2F5PsZdVRwiGRuckT3j9k2Q
        jlKQi/97rKY+VwL1TaNX3Z0xtCdGbKKtxEsbkDLj2FdOH2DRciVJWA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-06T20:11:43Z"
  mac: ENC[AES256_GCM,data:7FXHYnlfZGrUee1hxyFGfnGlXWIvKZ9FLXdoSUiNW2Gay1wvqkbomzEnoDUW5r1OqiXEpuCkjskKKCv6VQMndUtNO9rD2yPEyIml1meajntyyJSTC8ERIaz/Up7mlvmF5GUwqCCEDVBhKnScCykM/3M7bFvZN1fS1qjyR6tENP8=,iv:Hd51IxTa/iUq92N62ZcplUifXvVZgKu8HmtwC+OF32I=,tag:uK7OWA8ngKSIjcNeS2SrLQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
