apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:mgygSNFsbeaeGkM=,iv:5YvzXR7LZtEYCkOxhkyOFo1TH0V6seR0MVFFSDTkyi0=,tag:zyOBNoV1O+Fw0CNgIPUrIQ==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:jfifGdWVYKjaXJOquL1p,iv:BaZ8tcysLibpe3+EHW5r9VnCFUKBNKktKj4YuxHVSmE=,tag:HlrYal1xXiq1llfTqk7mXw==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:22bCS5Fau4s3MI/pXPfLIYBP2sjA2V+FFhYJN9ZdEHFE4/qi,iv:KF6FLDjv1KGt4kD7c0JaJXSFHO7nmZX14R3T72qNlps=,tag:dndQjalnLFpAtaNj5vaQNw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18rs8lggg0adpzfkgpz5zgja9ayu5d9m3hzedwr6vyjrzj4h3afss5jxglt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4R3JRcGlRdU10T05YM2F6
        ajZaRjRTTW1yc0l4L2FXVnRsUEZtVitzaWxFCjBsWkxZZzJDSXdDQ1JKL0xoQk1B
        bFRJdDJtSzVNRGRwZHNZTWJ6eHZVOE0KLS0tIFowcEdnT3Z0N1ltRy9lTW8yL1B6
        SDIwcURHNFR0ekExSm1vZlVnbDJVdEUKlmLV6esaWBGL4D6gZBn4FzNEkCCRib+S
        3kr0JpuYSjlp8HLkKH0gJ3c04GgYUf8wUtJxcnnCK2vFUB1RxHJarQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-09T06:38:28Z"
  mac: ENC[AES256_GCM,data:rASZxzbOEIShFsMJiNAMI/ngKES3sE95pqgsRLfhBz7RJBQsvJ+al/9ih6fTrzpiluNcxfLXDfj4+lEuu6j05T0F7mB+xIlUFC0SXZ0RQFOyJgYfYDOX5HL8DxcSx1QRKZA0qvFKbeN9+7/WndqChtwgjZNQ3VOIvzLAX9jQgYo=,iv:Zqt3OcCpwKtz5/JlSd/YKWIH0i0fyaWz9ei+VKzsetk=,tag:gl7EReWSOdY4osgzyqdmFw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
