apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:e2FNVl7CuwOm9Ek=,iv:AM9UeuyHTkboNPppapo0p9oz3x0BPmTaXm8twqrBxxc=,tag:7XbS9CfWbrXB2G9LbdExNw==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:hLgguuNsYWsFKw8cMwYB,iv:QMMDxlYdVGEdHsl6lX2nHWVBwfOTO9OXHk6LKt7saBI=,tag:wn6C+uiXlNP48nOS7FU6Ow==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:XPsbU6O79+jZYZ+/6hXLBZkuiqwgepPgwfuG6cyDgq+arMmf,iv:XljY2nHQ885mMyoNqB2eqjJ4bMbQx2lLhSbN+zKeE8A=,tag:BOC2SJevAzi1w7oiLpFD8Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18rs8lggg0adpzfkgpz5zgja9ayu5d9m3hzedwr6vyjrzj4h3afss5jxglt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQU9RaDNEOHVuSG1ZM2tB
        dW9NdFcxY1ljeHdhSlBWbFM0NXdNT0Z4Y2hrCktENGtKNVZ6UWRxSTZyREU3U0Z5
        UUVHbTBHbGlVR3NFaWdES3RDVDF3eXcKLS0tIHJnSW9rcXdtMVJzbTlEREtPK2Fa
        Uy9sOFdWMzNDMVJPNFVRZVcvRGZ5TkkKugrUw2tQxhf56vm2v77COcGl92RXPKCr
        e1+XtFVSa7urVxGyh2W+YP1fKXT/teuJXZOoAOUIC5yqwIDkdFY+2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-09T08:44:49Z"
  mac: ENC[AES256_GCM,data:Z3De2/n+PC9Gi7sbfxVzEiByglX0XaOPmJZ/FNKK69/mh+Ne0/zFLp/cOqcYfdsNFf83T/i5E9D5YeAnzpmRg0B8ijcQDdqgXAO3/g8Kd4JrPORaSzf4X1KzAA2SQsOdVFJ0Fi0CRVl4OzZV4fkH8ft1tdBFQp+crfz2fRCIbQU=,iv:Jav1HWl8r2lSA+s0924WMF6yYyFOQwsVe+H8BKpDEJA=,tag:GkZd7DcSqVfd7kxsrfdp4w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
