---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: freenas-api-iscsi-values
    files:
      - values.yaml=./helm/values.yaml
secretGenerator:
  - name: freenas-api-iscsi-secrets
    files:
      - values.yaml=./helm/secrets.sops.yaml
configurations:
  - ./helm/kustomizeconfig.yaml