# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: freenas-api-iscsi-secret
data:
    values.yaml: ENC[AES256_GCM,data:T/QodK3HWl6uRTY5+q2RFd6U40kUAyMUW0gdE+AzyXM53En4bG1Y8O+D3kXOXdJEDpTqB5DR+aJvnOHCRco1g7j/quZha8I8d+3dTCnJK6I+6+C5d8gn4dSZQjAdTgRbyeCLiQ09Q5o9YWCdXlbmggKhzKObfuhU3tVrAOLft6gclxT3Ytj07GD5C3Si4oHMiMNe4qTkxjFolLt7,iv:6YoSlq27y2poW9M/2mbFdXqU8fjN7ByDklx1vhP0FDU=,tag:ar2z503/0q2X9R7o7QrjBQ==,type:str]
sops:
    age:
        - recipient: age1r9x82vylxeu648374ysaydeawu0a2xankc3fclw060ps2cqrsucq4zwtd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRVN1RDI1Wmwxam40cHpS
            WHcwRFFwZmc3SkdWTURsWXlGdTNKTElvWW1RClJaWVczYzduZDhrMEU2TFp1ZTBK
            U01IK2lvYlhJK1dsVURwV0x6R3NBTlkKLS0tIGYraWNiSDZJdGlXUk03M2NWbUMz
            WU50MzRiUysvaUtzamJvL2N2Q1laQ1kK0AaKU/Kto2F5PsZdVRwiGRuckT3j9k2Q
            jlKQi/97rKY+VwL1TaNX3Z0xtCdGbKKtxEsbkDLj2FdOH2DRciVJWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-18T23:13:54Z"
    mac: ENC[AES256_GCM,data:n/0wTjRn1zDG/yYYBvMriBSbgqW3OvYgvRdrWnY1hzjd3jqgPsZIEOvLkHeT86JqZP8FbZJ20sMJWffYY02SUhnO5skkKETXLSHF2WVqSpYpx4OeZR+hE4Jxml+6NhP/GpGYUt9XXLepK91+MGCo/3B1lf1araRevwALua79i9k=,iv:SKjnOl9xN8c8RduzXuXHSxKWvAhcbht7Vd6i4Jd6lwA=,tag:e0NGC+KFB09vcdh3qdlXKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.1
