apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:7xXvwONU9f87XnVQLadoxK8KEud1NyelmFHvpUqVXlLhO7xTsqNOFw==,iv:bOPfDDI39EXqR9sX8aSeJjNwNpyZN6NBnCQhqWa6o/A=,tag:v4V7D5bpwNJcN8cVWzpjUA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18rs8lggg0adpzfkgpz5zgja9ayu5d9m3hzedwr6vyjrzj4h3afss5jxglt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSUpBVk05RDFFeUFpb0g0
        VlhWNW1OM1BzdGJlM1hOV1FaVlByV1dOOFdnCnJYY09DRU1jWWFBRWdZZ1Q4d09l
        RFdMalNFNVZ6T2toZ3RzemR6a295M3MKLS0tIEdEWHF4N2hXeEZ2eFRoeUJJWUhM
        bEVDNmpHZ1FXRmZ4bFlTREcyTC8ySE0KZDMtfT9N0zursTHpbFADJXUUCKLqtwIs
        KMAYGEPvqfygS/qaUyvVjS1RlwXJSrGk2MEU8e8IHcsQ9G1+vMAFMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-09T08:44:49Z"
  mac: ENC[AES256_GCM,data:h0u0ZOfQ2VfQDEkl4NvOUd4dir7lKmN2sJvhg7KkkoWGh94vj+bcvmYiTYjknm0Z35haO3qSLz1anPxUnB9WtdXYXBad2oRXIQXxhOhTKTwFseDkZf0nVnN/k9FwHzuCUOV0w9HeXTVevH/hJokRi9eBMhJF2f0HxNUXJbvJwXM=,iv:NejZi/53An6GMxZC9nlgL5qnP3W+Dz0/Ydwf1Qp+RvE=,tag:Hgfvcq4XQK93M87aiGfNuw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
