apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:lfZoLSznT0Q4SZa2DLJ7g2YN+0FdNLbTMYTixClK1iTF1bX1ypPmAA==,iv:yKm5TPCG8ZdWL/DW8955f3tJXMVa9trS04T0oHC32L8=,tag:SmQlOLwAnN6a+niwvq253Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18rs8lggg0adpzfkgpz5zgja9ayu5d9m3hzedwr6vyjrzj4h3afss5jxglt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUDQrK1N5c3ZrR2p2aUxj
        OHZSdXNLY0NGYjNUbUdFcWdVSXZGU2l2MlVVCjg3YTZrYjZnR0I3MHFVQnBaSDFQ
        QUcwSVoySkJpcGs1QU5zU0Jua1NZQTAKLS0tIEFJQjdUejEwQzhjdTZVRVMzVmlM
        bVlJVTZyek1XeGlRSWRaY3UyQmJqQ0EKqr/qwJ9x/MWRUxJ+lOHyiuZO9IuyIMRp
        YKlkH0ikemf6jksL/soDzFrGKAsQxPm2T7duFfLCFY+I/n77TqmTkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-09T06:38:28Z"
  mac: ENC[AES256_GCM,data:mmE3R9dYaUT5Vh7B4vjUX6Zkx76PHHYstUSyP8ykfXpbCXmeUISSrkwlOPe9xhChUdtszRhxvVb/W3mqyPIAY7vgJhbbMEw2ofApaHO5Yr70c1urp1qbXH3ZuWmjfNhrXsQWExl3x/2nNgfp7Kh6J06l/uUZRGhTdlXv+5RR0QY=,iv:mY4XWAuatmW2VKYqNfWIDzGVVDxpRBf82vJw9+32gAQ=,tag:lJ08pdr57H3tyTER+7VkqQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
