---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: add-pod-security-label
labels:
  pod-security.kubernetes.io/enforce: privileged
fieldSpecs:
  - kind: Namespace
    path: metadata/labels